name: hoplon
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/hoplon#readme.md
license: MIT
description: Erlang/Elixir type guards for javascript, but with every imaginable method.
repository: https://github.com/sourcevault/hoplon.git
version: 0.0.23
main: dist/main.js
scripts:
  "test": "make travis"
dependencies:
  ramda: "0.26.1"
  chalk: "2.4.2"
  pretty-error: "2.1.1"
devDependencies:
  benchmark: "*"
keywords:
  - pattern matching
  - guards
  - guard-js
  - functional
  - immutable
  - simple
  - utils
  - livescript
