name: hoplon
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/hoplon#readme.md
license: MIT
description: Elixir type guards for javascript, but better.
repository: https://github.com/sourcevault/hoplon.git
version: 0.0.1
main: dist/main.js
scripts:
  "test": "make travis"
dependencies:
  seamless-immutable: "7.1.4"
  ramda: "0.26.1"
  json-stringify-pretty-compact: "2.0.0"
keywords:
  - simple
  - functional
  - ES6 Proxy
  - immutable
  - livescript
  - guard-js
